### ISSUE TITLE
Group Pins at same Location

### ISSUE THREAD

**Issue by Mojo90** [phonegap-googlemaps-plugin/cordova-plugin-googlemaps#663]
I have a future/feature Request. Is there a way to easily group Markes at the same location?
And if you zoom out und much pins are shown group them as well as zooming out and if you zoom in again they get respectively ungrouped.
Is this possible?
An example would be http://ban.jo
I already implemented this on native iOS Code for Apple Maps approx 2 years ago and now interested to have this for this maps plugin on Android and iOS. I would contribute to iOS side if possible...

**Comment by Hirbod** [comment]
Marker Clustering is planned for a year. Actually we had a funding, but masashi dropped the development. Don't know what happened to the funded money, but seems like it's gone.

Acutally, android development was nearly ready, but I think it should be done from scratch.

Google ships a utility for that (android only) 
I'm not experienced enough, but I would love to see that someone built this into our plugin:

https://developers.google.com/maps/documentation/android-api/utility/marker-clustering

There are some Google Maps SDK for iOS Clustering Tools outthere, someone need just to integrate this.

Are you interessed mojo?

**Comment by Hirbod** [comment]
Fork Plugin, Add  <framework src="com.google.maps.android:android-maps-utils:+" /> into the plugin.xml - and than, someone could start building the marker cluster feature with dead simple options.

**Comment by Mojo90** [comment]
Yep I am interested. As I mentioned I already I wrote own methods for native iOS and thus would rather support iOS side. But could have a look at Clustering tools and I think is not so rocket science as 3 years ago there I had to investigate very deep but worked very well in the end :D 
And when iOS works and nobody else will takeover Android I can have a look at Android side. I have to push an update and thus will be busy till end of next week I think but then I'll look at it :)

**Comment by jsappme** [comment]
+1

**Comment by Hirbod** [comment]
I've found an experienced android and iOS developer, which I'm going to pay myself for the clustering feature. I will also start a funding on this soon. I guess you don't need to dig into this anymore @Mojo90

**Comment by jsappme** [comment]
Hirbod you re the best.

**Comment by johnrobertcobbold** [comment]
+1 on you are the best

**Comment by Mojo90** [comment]
oh great :)
