### ISSUE TITLE
Update Google Maps SDK for iOS 1.10.4 - October 2015

### ISSUE THREAD

**Issue by dukhanov** [phonegap-googlemaps-plugin/cordova-plugin-googlemaps#675]
Hello Hirbod,
I noticed the Google has updated Google Maps SDK for iOS. 
https://developers.google.com/maps/documentation/ios-sdk/releases?hl=en

The update contains fixes, which sometimes happens in my cordova google maps application.

Could you please say, the optimistic date, when you can update the repository?https://github.com/nightstomp/googlemaps-ios-sdk-for-phonegap

Thanks a lot!

**Comment by Hirbod** [comment]
Hi @dukhanov,

optimistic I would say, I've already updated it :P
Just reinstall plugin.

**Comment by dukhanov** [comment]
You are awesome.
Thanks again!
