### ISSUE TITLE
Android: addMarker results in weird behaviour with JS breakpoints in Chrome debugger

### ISSUE THREAD

**Issue by n00dl3** [phonegap-googlemaps-plugin/cordova-plugin-googlemaps#677]
Hi, @Hirbod 
I experienced strange behaviour (once again, lucky me! :smile: ) lately :

I set some breakpoints in my JS code via chrome's js debugger, on the `map.addMarker()` 's callback these breakpoints are reached by the interpreter but it can't maintain them, I mean it hang for a while (say half a second)  and the cursor just ignore them and keep executing the code, it's flagrant in a loop. 

I don't think it comes from Chrome/Chromium, because it's the only place where breakpoints aren't taken in account.

It's not a big deal, because the code is executed, and it works but it makes the JS so hard to debug. I didn't investigate about that yet, but I will try to ASAP, maybe this weekend.

**Comment by n00dl3** [comment]
I think it's a concurrent execution issue, i don't see any other explaination for now...

**Comment by Hirbod** [comment]
I'm going to close this, until you have find out more. Seems very specific
