### ISSUE TITLE
Google places autocomplete for android

### ISSUE THREAD

**Issue by anshul** [phonegap-googlemaps-plugin/cordova-plugin-googlemaps#678]
Any chance we can expose https://developers.google.com/places/android-api/autocomplete via this plugin?

**Comment by Hirbod** [comment]
Some day, yes. My time is very limited currently.

**Comment by Mojo90** [comment]
@anshul 
Thats funny today I started to implement autocomplete via: https://developers.google.com/places/javascript/

Only manko I currently have is that I get no callback when I click on a place/city (google.maps.event.addListener(autocomplete, 'place_changed', function() {});), but I hope, that I get it working soon.

**Comment by Hirbod** [comment]
I bet that you have fastclick lib inside your app. (Auto added in Onsen and Ionic)

This will fix it:

```js
        // this workaround is needed because of "fastclick"
        $(document).on({
            'DOMNodeInserted': function () {
                $('.pac-item, .pac-item span', this).addClass('needsclick');
            }
        }, '.pac-container');
        // end google maps places autocomplete workaround
```

**Comment by Mojo90** [comment]
DAMN. Just wanted to copy this now. Just found stackoverflow after hours of googling ;)
http://stackoverflow.com/questions/9972080/cant-tap-on-item-in-google-autocomplete-list-on-mobile

thx Hirbod!

**Comment by Hirbod** [comment]
;)

https://github.com/OnsenUI/OnsenUI/issues/420

**Comment by ronyrun** [comment]
Hello guys,
is it possible to use this plugin to get places from lng, lat and radius ?

**Comment by Hirbod** [comment]
not with our plugin. If you need places, you need to use the JS Places lib

**Comment by ronyrun** [comment]
OK thank you @Hirbod for this very wuick answer :)

**Comment by ituhin** [comment]
google places api plugin for cordova will be very much useful.... that javascript api is a pain in terms of mobile app UX. and i am unable to use that google places webservice (server side) api in my ionic/cordova app due to cross domain issues.
but i dont get one thing why foursquare server side api is working in my cordova app but not google places server side api.

**Comment by Hirbod** [comment]
Well this should be possible with the server side solution. Use php and make a socket/curl request or use php-geolocation and pass back the results in your app. Im doing something similar. Use the whitelist plugin to whitelist your domain for JS request with Ajax to your server. Your request should hold geodata from users device.

**Comment by ituhin** [comment]
lol... yea thought of that. then that will add a bit lag, and didnt feel good about it. then i found this in goog place js api... -> new google.maps.places.AutocompleteService();
so using that.

but i still dont get... why foursquare server side api working but not google place server side api. both should face the same problem. 
both the domains are whitelisted in the app.

**Comment by Hirbod** [comment]
Well do some more debug. Nevertheless, this is not a support forum. Please use StackOverflow
