### ISSUE TITLE
Plug-in not compatible with cordova ios 4.0

### ISSUE THREAD

**Issue by jvence** [phonegap-googlemaps-plugin/cordova-plugin-googlemaps#680]
Been testing ios 4.0 (see https://shazronatadobe.wordpress.com) and tried using this google maps plugin but it won't compile. Here are some of the errors:

Plugins/plugin.google.maps/GroundOverlay.m:99:43: Property 'request' not found on object of type 'UIView *'

Plugins/plugin.google.maps/KmlOverlay.m:40:43: Property 'request' not found on object of type 'UIView *'

Plugins/plugin.google.maps/KmlOverlay.m:584:56: No known instance method for selector 'initWithWebView:'

[![Bountysource](https://www.bountysource.com/badge/issue?issue_id=27551830)](https://www.bountysource.com/issues/27551830-plug-in-not-compatible-with-cordova-ios-4-0?utm_source=27551830&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by Hirbod** [comment]
I did not test WKWebView

**Comment by jvence** [comment]
It's close to being released so it might be a good idea to update the plugin.

**Comment by Hirbod** [comment]
It's definitely on the list..

**Comment by Hirbod** [comment]
https://github.com/apache/cordova-ios/blob/master/guides/API%20changes%20in%204.0.md

Changes are huge. They have removed some classes we use, also writeJavascript, which is important for the triggering the events. I could add the old classes as legacy, but that would be the wrong way. Definitely need to dig into this soon. But currently, mostly all my plugins are broken (even the Camera plugin)

We will need to wait some time

**Comment by jvence** [comment]
Yes it is a substantial upgrade which should see very good performance improvements for cordoba-based apps. I've been testing it and I have an app with around 20 plug-ins. 18 worked fine but 2 did not including this google maps (the other one was just fixed). Everyone will be upgrading to 1.4 as it's a major advancement for hybrid app.

**Comment by Hirbod** [comment]
I know it's a huge benefit, but it's not stable enough currently. We will have to wait, till it's out

**Comment by Hirbod** [comment]
I'm going to close this for now, as it's still in progress. I can't imagine that just 2 plugins won't work. Cordova IOS-4 has removed CDVJSON, nearly all plugins are using this one.

The changes are huge and this will take a while
